name: Build and Push Spark 3.5 Image

on:
  workflow_dispatch:

jobs:
  build_and_push_spark_image:
    name: Build spark base image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build, tag, and push image to Docker Hub
      env:
        REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        REPOSITORY: spark
        IMAGE_TAG: v3.5.0-hadoop3
      run: |
        cd $IMAGE_PATH
        docker buildx create --name=container --driver=docker-container --use --bootstrap
        ./bin/docker-image-tool.sh -r $REGISTRY -t $IMAGE_TAG -p ./kubernetes/dockerfiles/spark/bindings/python/Dockerfile -X build        
env:
  IMAGE_PATH : "spark-3.5.0-bin-hadoop3"